name: Terraform Scan and Deploy

on:
  workflow_dispatch:
  push:
    branches:
      - main

permissions:
  security-events: write
  contents: read

jobs:
  tfsec-and-deploy:
    name: TFsec Scan + Terraform Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # ----------------------
      # Install Terraform
      # ----------------------
      - name: Install Terraform
        run: |
          TERRAFORM_VERSION="1.12.2"
          curl -sSLo terraform.zip https://releases.hashicorp.com/terraform/${TERRAFORM_VERSION}/terraform_${TERRAFORM_VERSION}_linux_amd64.zip
          unzip terraform.zip
          sudo mv terraform /usr/local/bin/
          terraform -version

      # ----------------------
      # Terraform Init
      # ----------------------
      - name: Terraform Init
        run: terraform init

      # ----------------------
      # Install tfsec
      # ----------------------
      - name: Install tfsec
        run: |
          curl -sSL https://raw.githubusercontent.com/aquasecurity/tfsec/master/scripts/install_linux.sh | bash
          tfsec --version

      # ----------------------
      # Run tfsec
      # ----------------------
      - name: Run tfsec
        run: |
          mkdir -p tfsec-reports
          tfsec . --format sarif --soft-fail > tfsec-reports/tfsec-results.sarif
          tfsec . --format html --soft-fail > tfsec-reports/tfsec-report.html

      - name: Upload SARIF to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: tfsec-reports/tfsec-results.sarif

      - name: Upload HTML report as artifact
        uses: actions/upload-artifact@v4
        with:
          name: tfsec-html-report
          path: tfsec-reports/tfsec-report.html

      # ----------------------
      # Configure AWS Credentials
      # ----------------------
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1   # change region if needed

      # ----------------------
      # Terraform Apply (deploy)
      # ----------------------
      - name: Terraform Apply
        run: |
          terraform plan -out=tfplan
          terraform apply -auto-approve tfplan

      # ----------------------
      # Output ALB URL
      # ----------------------
      - name: Show ALB URL
        run: terraform output alb_url
